"use strict";

const pickEntries = require("../pick-entries");

describe("pick entries test suite", () => {
  it("should pick entries correctly case A", () => {
    // SETUP
    const entry = {
      "api::chapter.chapter[1].title": "1. Addition",
      "api::chapter.chapter[1].lessons[1].title": "Lecture: Addition",
      "api::chapter.chapter[1].lessons[1].start_time": "2022-09-28T09:00:00.000Z",
      "api::chapter.chapter[1].lessons[1].duration": "03:00:00.000",
      "api::chapter.chapter[1].lessons[1].description": "## Description\n\nIn this lesson, we'll learn about addition and what rules to follow...",
      "api::chapter.chapter[1].lessons[1].lesson_type[1].__component": "lesson.lecture",
      "api::chapter.chapter[1].lessons[1].lesson_type[1].content": "You need to follow these rules:\na) add one number to the other\nb) do not subtract nor multiply\nc) ...",
      "api::chapter.chapter[1].lessons[2].title": "Test: Addition",
      "api::chapter.chapter[1].lessons[2].start_time": "2022-10-01T13:00:00.000Z",
      "api::chapter.chapter[1].lessons[2].duration": "02:00:00.000",
      "api::chapter.chapter[1].lessons[2].description": "Test your skills we've learnt in the previous lesson.",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].__component": "lesson.quiz",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].title": "Choose the correct answer",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[1].question": "1 + 1 = ",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[1].is_active": true,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[1].question_number": 1,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[2].question": "5 + 15 = ",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[2].is_active": false,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[2].question_number": 2,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].question": "How many cups are on the photo?",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].is_active": false,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].question_number": 3,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].name": "lidya-nada-BnzqQwerUOY-unsplash.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].alternativeText": "lidya-nada-BnzqQwerUOY-unsplash.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].caption": "lidya-nada-BnzqQwerUOY-unsplash.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].width": 3360,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].height": 5040,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.thumbnail.name": "thumbnail_lidya-nada-BnzqQwerUOY-unsplash.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.thumbnail.hash": "thumbnail_lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.thumbnail.ext": ".jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.thumbnail.mime": "image/jpeg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.thumbnail.width": 104,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.thumbnail.height": 156,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.thumbnail.size": 2.59,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.thumbnail.url": "/uploads/thumbnail_lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.large.name": "large_lidya-nada-BnzqQwerUOY-unsplash.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.large.hash": "large_lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.large.ext": ".jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.large.mime": "image/jpeg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.large.width": 667,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.large.height": 1000,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.large.size": 38.91,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.large.url": "/uploads/large_lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.medium.name": "medium_lidya-nada-BnzqQwerUOY-unsplash.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.medium.hash": "medium_lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.medium.ext": ".jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.medium.mime": "image/jpeg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.medium.width": 500,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.medium.height": 750,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.medium.size": 24.62,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.medium.url": "/uploads/medium_lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.small.name": "small_lidya-nada-BnzqQwerUOY-unsplash.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.small.hash": "small_lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.small.ext": ".jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.small.mime": "image/jpeg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.small.width": 333,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.small.height": 500,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.small.size": 12.98,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].formats.small.url": "/uploads/small_lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].hash": "lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].ext": ".jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].mime": "image/jpeg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].size": 1536.82,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].url": "/uploads/lidya_nada_Bnzq_Qwer_UOY_unsplash_1c85b31b12.jpg",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].questions[3].assets[13].provider": "local",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].answers[1].question_number": 1,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].answers[1].correct_answer": "2",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].answers[2].question_number": 2,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].answers[2].correct_answer": "20",
      "api::chapter.chapter[1].lessons[2].lesson_type[1].answers[3].question_number": 3,
      "api::chapter.chapter[1].lessons[2].lesson_type[1].answers[3].correct_answer": "15",
    };

    const pickPaths = [
      "api::chapter.chapter.title",
      "api::chapter.chapter.id",
    ];

    const transferSetupModel = {
      __model__: true,
      title: true,
      lessons: null,
    };

    // EXECUTE
    const result = pickEntries(entry, pickPaths, transferSetupModel);

    // VERIFY
    const expected = {
      "api::chapter.chapter[1].title": "1. Addition",
    };

    expect(result).toEqual(expected);
  });

  it("should pick entries correctly case B", () => {
    // SETUP
    const entry = {
      "api::cookbook.cookbook[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].author_name": "David V.",
      "api::cookbook.cookbook[1].pages": 368,
      "api::cookbook.cookbook[1].recipes[1].name": "Potato Salad",
      "api::cookbook.cookbook[1].recipes[1].recipe": "Peel the potatoes, mix it with all the ingredients and you're done. Bon apetit!",
      "api::cookbook.cookbook[1].recipes[1].estimated_cook_time": "00:30:00.000",
      "api::cookbook.cookbook[1].recipes[1].difficulty": "easy",
      "api::cookbook.cookbook[1].recipes[1].author_name": "Mr. Potato Head",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image_title": "Raw potatoes",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image_description": "Fresh!",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].name": "rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].alternativeText": "rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].caption": "rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].width": 2268,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].height": 4032,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.thumbnail.name": "thumbnail_rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.thumbnail.hash": "thumbnail_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.thumbnail.ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.thumbnail.mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.thumbnail.width": 88,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.thumbnail.height": 156,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.thumbnail.size": 5.35,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.thumbnail.url": "/uploads/thumbnail_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.large.name": "large_rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.large.hash": "large_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.large.ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.large.mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.large.width": 563,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.large.height": 1000,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.large.size": 108.15,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.large.url": "/uploads/large_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.medium.name": "medium_rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.medium.hash": "medium_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.medium.ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.medium.mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.medium.width": 422,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.medium.height": 750,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.medium.size": 65.52,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.medium.url": "/uploads/medium_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.small.name": "small_rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.small.hash": "small_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.small.ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.small.mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.small.width": 281,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.small.height": 500,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.small.size": 34.23,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].formats.small.url": "/uploads/small_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].hash": "rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].size": 1081.59,
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].url": "/uploads/rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image[6].provider": "local",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image_title": "Salad",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image_description": "Yummy!",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].name": "jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].alternativeText": "jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].caption": "jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].width": 4608,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].height": 3456,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.thumbnail.name": "thumbnail_jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.thumbnail.hash": "thumbnail_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.thumbnail.ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.thumbnail.mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.thumbnail.width": 208,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.thumbnail.height": 156,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.thumbnail.size": 9.03,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.thumbnail.url": "/uploads/thumbnail_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.large.name": "large_jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.large.hash": "large_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.large.ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.large.mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.large.width": 1000,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.large.height": 750,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.large.size": 102.77,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.large.url": "/uploads/large_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.medium.name": "medium_jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.medium.hash": "medium_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.medium.ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.medium.mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.medium.width": 750,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.medium.height": 563,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.medium.size": 66.26,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.medium.url": "/uploads/medium_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.small.name": "small_jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.small.hash": "small_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.small.ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.small.mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.small.width": 500,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.small.height": 375,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.small.size": 35.17,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].formats.small.url": "/uploads/small_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].hash": "jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].ext": ".jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].mime": "image/jpeg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].size": 1664.79,
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].url": "/uploads/jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image[7].provider": "local",
      "api::cookbook.cookbook[1].recipes[1].ingredients[1].name": "Potatoes",
      "api::cookbook.cookbook[1].recipes[1].ingredients[1].amount": 2,
      "api::cookbook.cookbook[1].recipes[1].ingredients[1].unit": "kg",
      "api::cookbook.cookbook[1].recipes[1].ingredients[1].is_required": true,
      "api::cookbook.cookbook[1].recipes[1].ingredients[2].name": "Peas",
      "api::cookbook.cookbook[1].recipes[1].ingredients[2].amount": 1,
      "api::cookbook.cookbook[1].recipes[1].ingredients[2].unit": "can",
      "api::cookbook.cookbook[1].recipes[1].ingredients[2].is_required": true,
      "api::cookbook.cookbook[1].recipes[1].ingredients[3].name": "Corn",
      "api::cookbook.cookbook[1].recipes[1].ingredients[3].amount": 0.5,
      "api::cookbook.cookbook[1].recipes[1].ingredients[3].unit": "can",
      "api::cookbook.cookbook[1].recipes[1].ingredients[3].is_required": true,
      "api::cookbook.cookbook[1].recipes[1].ingredients[4].name": "Mayo",
      "api::cookbook.cookbook[1].recipes[1].ingredients[4].amount": 4,
      "api::cookbook.cookbook[1].recipes[1].ingredients[4].unit": "spoons",
      "api::cookbook.cookbook[1].recipes[1].ingredients[4].is_required": true,
      "api::cookbook.cookbook[1].recipes[1].ingredients[5].name": "Cheese",
      "api::cookbook.cookbook[1].recipes[1].ingredients[5].amount": 1,
      "api::cookbook.cookbook[1].recipes[1].ingredients[5].unit": "block",
      "api::cookbook.cookbook[1].recipes[1].ingredients[5].is_required": true,
      "api::cookbook.cookbook[1].recipes[1].ingredients[6].name": "Apple",
      "api::cookbook.cookbook[1].recipes[1].ingredients[6].amount": 1,
      "api::cookbook.cookbook[1].recipes[1].ingredients[6].unit": "pcs",
      "api::cookbook.cookbook[1].recipes[1].ingredients[6].is_required": false,
      "api::cookbook.cookbook[1].gallery[1].annotation": "Check out our delicious meal, then read on and dive into the culinary heaven!",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image_title": "Cookbook",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image_description": "Booklet II",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].name": "dan-gold-5O1ddenSM4g-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].alternativeText": "dan-gold-5O1ddenSM4g-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].caption": "dan-gold-5O1ddenSM4g-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].width": 6000,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].height": 3376,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.thumbnail.name": "thumbnail_dan-gold-5O1ddenSM4g-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.thumbnail.hash": "thumbnail_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.thumbnail.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.thumbnail.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.thumbnail.width": 245,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.thumbnail.height": 138,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.thumbnail.size": 7.44,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.thumbnail.url": "/uploads/thumbnail_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.large.name": "large_dan-gold-5O1ddenSM4g-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.large.hash": "large_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.large.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.large.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.large.width": 1000,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.large.height": 563,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.large.size": 52.67,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.large.url": "/uploads/large_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.medium.name": "medium_dan-gold-5O1ddenSM4g-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.medium.hash": "medium_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.medium.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.medium.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.medium.width": 750,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.medium.height": 422,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.medium.size": 35.15,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.medium.url": "/uploads/medium_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.small.name": "small_dan-gold-5O1ddenSM4g-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.small.hash": "small_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.small.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.small.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.small.width": 500,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.small.height": 281,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.small.size": 19.95,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].formats.small.url": "/uploads/small_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].hash": "dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].size": 972.68,
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].url": "/uploads/dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image[9].provider": "local",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image_description": "The booklet and leaves and fork.",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].name": "heather-ford-G4LFhuLXhLE-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].alternativeText": "heather-ford-G4LFhuLXhLE-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].caption": "heather-ford-G4LFhuLXhLE-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].width": 6127,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].height": 3844,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.thumbnail.name": "thumbnail_heather-ford-G4LFhuLXhLE-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.thumbnail.hash": "thumbnail_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.thumbnail.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.thumbnail.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.thumbnail.width": 245,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.thumbnail.height": 154,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.thumbnail.size": 9.54,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.thumbnail.url": "/uploads/thumbnail_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.large.name": "large_heather-ford-G4LFhuLXhLE-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.large.hash": "large_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.large.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.large.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.large.width": 1000,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.large.height": 628,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.large.size": 117.56,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.large.url": "/uploads/large_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.medium.name": "medium_heather-ford-G4LFhuLXhLE-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.medium.hash": "medium_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.medium.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.medium.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.medium.width": 750,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.medium.height": 471,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.medium.size": 66.32,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.medium.url": "/uploads/medium_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.small.name": "small_heather-ford-G4LFhuLXhLE-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.small.hash": "small_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.small.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.small.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.small.width": 500,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.small.height": 314,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.small.size": 31.42,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].formats.small.url": "/uploads/small_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].hash": "heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].size": 6971.47,
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].url": "/uploads/heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image[11].provider": "local",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image_title": "Spices",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].name": "calum-lewis-vA1L1jRTM70-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].alternativeText": "calum-lewis-vA1L1jRTM70-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].caption": "calum-lewis-vA1L1jRTM70-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].width": 3569,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].height": 5353,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.thumbnail.name": "thumbnail_calum-lewis-vA1L1jRTM70-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.thumbnail.hash": "thumbnail_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.thumbnail.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.thumbnail.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.thumbnail.width": 104,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.thumbnail.height": 156,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.thumbnail.size": 5.55,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.thumbnail.url": "/uploads/thumbnail_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.large.name": "large_calum-lewis-vA1L1jRTM70-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.large.hash": "large_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.large.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.large.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.large.width": 667,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.large.height": 1000,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.large.size": 116.32,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.large.url": "/uploads/large_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.medium.name": "medium_calum-lewis-vA1L1jRTM70-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.medium.hash": "medium_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.medium.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.medium.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.medium.width": 500,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.medium.height": 750,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.medium.size": 72.75,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.medium.url": "/uploads/medium_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.small.name": "small_calum-lewis-vA1L1jRTM70-unsplash.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.small.hash": "small_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.small.ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.small.mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.small.width": 333,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.small.height": 500,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.small.size": 36.52,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].formats.small.url": "/uploads/small_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].hash": "calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].ext": ".jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].mime": "image/jpeg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].size": 2305.97,
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].url": "/uploads/calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image[10].provider": "local",
      "api::cookbook.cookbook[1].used_in_restaurants[1].name": "Hungry Window",
      "api::cookbook.cookbook[1].used_in_restaurants[1].description": "Oriental street food in your mouth quick and easy!",
      "api::cookbook.cookbook[1].used_in_restaurants[1].established_at": "2022-10-01",
      "api::cookbook.cookbook[1].used_in_restaurants[1].is_franchise": false,
      "api::cookbook.cookbook[1].used_in_restaurants[1].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[1].cuisine": "Thai",
      "api::cookbook.cookbook[1].used_in_restaurants[1].capacity": 68,
      "api::cookbook.cookbook[1].used_in_restaurants[1].our_story": "There's **more** behind! Check out our story at [Localazy](https://localazy.com).\n\n![Logo_sq-01.png](/uploads/Logo_sq_01_08b9bb6be1.png)",
      "api::cookbook.cookbook[1].used_in_restaurants[1].menu[1].name": "Curry Soup",
      "api::cookbook.cookbook[1].used_in_restaurants[1].menu[1].price": 5,
      "api::cookbook.cookbook[1].used_in_restaurants[1].menu[1].currency": "$",
      "api::cookbook.cookbook[1].used_in_restaurants[1].menu[1].description": "_Super delicious soup._\n\n<u>Warning: Spicy as hell!</u>",
      "api::cookbook.cookbook[1].used_in_restaurants[1].menu[1].is_available": true,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].author_name": "David V.",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].pages": 368,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].name": "Potato Salad",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].recipe": "Peel the potatoes, mix it with all the ingredients and you're done. Bon apetit!",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].estimated_cook_time": "00:30:00.000",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].difficulty": "easy",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].author_name": "Mr. Potato Head",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].gallery[1].image_title": "Raw potatoes",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].gallery[1].image_description": "Fresh!",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].gallery[2].image_title": "Salad",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].gallery[2].image_description": "Yummy!",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[1].name": "Potatoes",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[1].amount": 2,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[1].unit": "kg",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[1].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[2].name": "Peas",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[2].amount": 1,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[2].unit": "can",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[2].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[3].name": "Corn",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[3].amount": 0.5,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[3].unit": "can",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[3].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[4].name": "Mayo",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[4].amount": 4,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[4].unit": "spoons",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[4].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[5].name": "Cheese",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[5].amount": 1,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[5].unit": "block",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[5].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[6].name": "Apple",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[6].amount": 1,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[6].unit": "pcs",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].recipes[1].ingredients[6].is_required": false,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].gallery[1].annotation": "Check out our delicious meal, then read on and dive into the culinary heaven!",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].gallery[1].main_image[3].image_title": "Cookbook",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].gallery[1].main_image[3].image_description": "Booklet II",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].gallery[1].gallery[5].image_description": "The booklet and leaves and fork.",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].gallery[1].gallery[4].image_title": "Spices",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].name": "Hungry Window",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].description": "Oriental street food in your mouth quick and easy!",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].established_at": "2022-10-01",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].is_franchise": false,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].cuisine": "Thai",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].capacity": 68,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].our_story": "There's **more** behind! Check out our story at [Localazy](https://localazy.com).\n\n![Logo_sq-01.png](/uploads/Logo_sq_01_08b9bb6be1.png)",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].menu[1].name": "Curry Soup",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].menu[1].price": 5,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].menu[1].currency": "$",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].menu[1].description": "_Super delicious soup._\n\n<u>Warning: Spicy as hell!</u>",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].menu[1].is_available": true,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].used_cookbooks[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].used_cookbooks[1].author_name": "David V.",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[1].used_cookbooks[1].pages": 368,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].name": "Blue Oyster",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].description": "See food? Better say Sea food!",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].established_at": "1822-07-09",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].cuisine": "Italian",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].capacity": 16,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].our_story": "Long tradition, wisdom given from generation to generation... Since 1822.",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].name": "Hungry Window",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].description": "Oriental street food in your mouth quick and easy!",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].established_at": "2022-10-01",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].is_franchise": false,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].cuisine": "Thai",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].capacity": 68,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].our_story": "There's **more** behind! Check out our story at [Localazy](https://localazy.com).\n\n![Logo_sq-01.png](/uploads/Logo_sq_01_08b9bb6be1.png)",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].name": "Michelin's",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].description": "The most fancy restaurant in the Solar System. Check out our menu created by the one and only Gordon Ramsay.",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].established_at": "2002-06-23",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].is_franchise": true,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].cuisine": "French",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].capacity": 148,
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].our_story": "## The most fancy restaurant in the Solar System.\n\nCheck out our menu created by ~~just a random guy~~ the one and only **Gordon Ramsay**.",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].used_cookbooks[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].used_cookbooks[1].author_name": "David V.",
      "api::cookbook.cookbook[1].used_in_restaurants[1].used_cookbooks[1].used_in_restaurants[3].used_cookbooks[1].pages": 368,
      "api::cookbook.cookbook[1].used_in_restaurants[3].name": "Blue Oyster",
      "api::cookbook.cookbook[1].used_in_restaurants[3].description": "See food? Better say Sea food!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].established_at": "1822-07-09",
      "api::cookbook.cookbook[1].used_in_restaurants[3].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].cuisine": "Italian",
      "api::cookbook.cookbook[1].used_in_restaurants[3].capacity": 16,
      "api::cookbook.cookbook[1].used_in_restaurants[3].our_story": "Long tradition, wisdom given from generation to generation... Since 1822.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].name": "Hungry Window",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].description": "Oriental street food in your mouth quick and easy!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].established_at": "2022-10-01",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].is_franchise": false,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].cuisine": "Thai",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].capacity": 68,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].our_story": "There's **more** behind! Check out our story at [Localazy](https://localazy.com).\n\n![Logo_sq-01.png](/uploads/Logo_sq_01_08b9bb6be1.png)",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].menu[1].name": "Curry Soup",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].menu[1].price": 5,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].menu[1].currency": "$",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].menu[1].description": "_Super delicious soup._\n\n<u>Warning: Spicy as hell!</u>",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].menu[1].is_available": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].author_name": "David V.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].pages": 368,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].recipes[1].name": "Potato Salad",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].recipes[1].recipe": "Peel the potatoes, mix it with all the ingredients and you're done. Bon apetit!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].recipes[1].estimated_cook_time": "00:30:00.000",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].recipes[1].difficulty": "easy",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].recipes[1].author_name": "Mr. Potato Head",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].gallery[1].annotation": "Check out our delicious meal, then read on and dive into the culinary heaven!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[1].name": "Hungry Window",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[1].description": "Oriental street food in your mouth quick and easy!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[1].established_at": "2022-10-01",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[1].is_franchise": false,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[1].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[1].cuisine": "Thai",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[1].capacity": 68,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[1].our_story": "There's **more** behind! Check out our story at [Localazy](https://localazy.com).\n\n![Logo_sq-01.png](/uploads/Logo_sq_01_08b9bb6be1.png)",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[3].name": "Blue Oyster",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[3].description": "See food? Better say Sea food!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[3].established_at": "1822-07-09",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[3].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[3].cuisine": "Italian",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[3].capacity": 16,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[1].used_cookbooks[1].used_in_restaurants[3].our_story": "Long tradition, wisdom given from generation to generation... Since 1822.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].name": "Michelin's",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].description": "The most fancy restaurant in the Solar System. Check out our menu created by the one and only Gordon Ramsay.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].established_at": "2002-06-23",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].is_franchise": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].cuisine": "French",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].capacity": 148,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].our_story": "## The most fancy restaurant in the Solar System.\n\nCheck out our menu created by ~~just a random guy~~ the one and only **Gordon Ramsay**.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].name": "Hungry Window",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].description": "Oriental street food in your mouth quick and easy!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].established_at": "2022-10-01",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].is_franchise": false,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].cuisine": "Thai",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].capacity": 68,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].our_story": "There's **more** behind! Check out our story at [Localazy](https://localazy.com).\n\n![Logo_sq-01.png](/uploads/Logo_sq_01_08b9bb6be1.png)",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].menu[1].name": "Curry Soup",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].menu[1].price": 5,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].menu[1].currency": "$",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].menu[1].description": "_Super delicious soup._\n\n<u>Warning: Spicy as hell!</u>",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].menu[1].is_available": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].used_cookbooks[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].used_cookbooks[1].author_name": "David V.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].supported_restaurants[1].used_cookbooks[1].pages": 368,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[2].name": "Crème brûlée",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[2].price": 24,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[2].currency": "$",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[2].description": "\n>Can't dream of a better one! Your tongue will be in the state of a pure happiness!\n\nSays Gordon himself.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[2].is_available": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[3].name": "Lobster",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[3].price": 99.9,
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[3].currency": "$",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[3].description": "Creamy, juicy, spicy!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].supported_restaurants[2].menu[3].is_available": false,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].author_name": "David V.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].pages": 368,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].name": "Potato Salad",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].recipe": "Peel the potatoes, mix it with all the ingredients and you're done. Bon apetit!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].estimated_cook_time": "00:30:00.000",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].difficulty": "easy",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].author_name": "Mr. Potato Head",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].gallery[1].image_title": "Raw potatoes",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].gallery[1].image_description": "Fresh!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].gallery[2].image_title": "Salad",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].gallery[2].image_description": "Yummy!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[1].name": "Potatoes",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[1].amount": 2,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[1].unit": "kg",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[1].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[2].name": "Peas",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[2].amount": 1,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[2].unit": "can",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[2].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[3].name": "Corn",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[3].amount": 0.5,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[3].unit": "can",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[3].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[4].name": "Mayo",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[4].amount": 4,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[4].unit": "spoons",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[4].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[5].name": "Cheese",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[5].amount": 1,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[5].unit": "block",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[5].is_required": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[6].name": "Apple",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[6].amount": 1,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[6].unit": "pcs",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].recipes[1].ingredients[6].is_required": false,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].gallery[1].annotation": "Check out our delicious meal, then read on and dive into the culinary heaven!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].gallery[1].main_image[3].image_title": "Cookbook",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].gallery[1].main_image[3].image_description": "Booklet II",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].gallery[1].gallery[5].image_description": "The booklet and leaves and fork.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].gallery[1].gallery[4].image_title": "Spices",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].name": "Hungry Window",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].description": "Oriental street food in your mouth quick and easy!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].established_at": "2022-10-01",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].is_franchise": false,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].cuisine": "Thai",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].capacity": 68,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].our_story": "There's **more** behind! Check out our story at [Localazy](https://localazy.com).\n\n![Logo_sq-01.png](/uploads/Logo_sq_01_08b9bb6be1.png)",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].menu[1].name": "Curry Soup",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].menu[1].price": 5,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].menu[1].currency": "$",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].menu[1].description": "_Super delicious soup._\n\n<u>Warning: Spicy as hell!</u>",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].menu[1].is_available": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].used_cookbooks[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].used_cookbooks[1].author_name": "David V.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[1].used_cookbooks[1].pages": 368,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].name": "Blue Oyster",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].description": "See food? Better say Sea food!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].established_at": "1822-07-09",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].cuisine": "Italian",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].capacity": 16,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].our_story": "Long tradition, wisdom given from generation to generation... Since 1822.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].name": "Hungry Window",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].description": "Oriental street food in your mouth quick and easy!",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].established_at": "2022-10-01",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].is_franchise": false,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].cuisine": "Thai",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].capacity": 68,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[1].our_story": "There's **more** behind! Check out our story at [Localazy](https://localazy.com).\n\n![Logo_sq-01.png](/uploads/Logo_sq_01_08b9bb6be1.png)",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].name": "Michelin's",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].description": "The most fancy restaurant in the Solar System. Check out our menu created by the one and only Gordon Ramsay.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].established_at": "2002-06-23",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].is_franchise": true,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].contact_email": "david@localazy.com",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].cuisine": "French",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].capacity": 148,
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].supported_restaurants[2].our_story": "## The most fancy restaurant in the Solar System.\n\nCheck out our menu created by ~~just a random guy~~ the one and only **Gordon Ramsay**.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].used_cookbooks[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].used_cookbooks[1].author_name": "David V.",
      "api::cookbook.cookbook[1].used_in_restaurants[3].used_cookbooks[1].used_in_restaurants[3].used_cookbooks[1].pages": 368,
    };

    const pickPaths = [
      "api::cookbook.cookbook.title",
      "api::cookbook.cookbook.recipes.name",
      "api::cookbook.cookbook.recipes.recipe",
      "api::cookbook.cookbook.recipes.gallery.image_title",
      "api::cookbook.cookbook.recipes.gallery.image_description",
      "api::cookbook.cookbook.recipes.author_name",
      "api::cookbook.cookbook.recipes.ingredients.name",
      "api::cookbook.cookbook.recipes.ingredients.unit",
      "api::cookbook.cookbook.gallery.main_image.image_title",
      "api::cookbook.cookbook.gallery.main_image.image_description",
      "api::cookbook.cookbook.gallery.gallery.image_title",
      "api::cookbook.cookbook.gallery.gallery.image_description",
      "api::cookbook.cookbook.gallery.optional_title",
      "api::cookbook.cookbook.gallery.annotation",
      "api::cookbook.cookbook.id",
    ];

    const transferSetupModel = {
      __model__: true,
      title: true,
      author_name: null,
      pages: null,
      recipes: {
        name: true,
        recipe: true,
        gallery: {
          image_title: true,
          image_description: true,
          image: null,
        },
        estimated_cook_time: null,
        difficulty: null,
        author_name: true,
        ingredients: {
          name: true,
          amount: null,
          unit: true,
          is_required: null,
        },
      },
      gallery: {
        main_image: {
          image_title: true,
          image_description: true,
          image: null,
        },
        gallery: {
          image_title: true,
          image_description: true,
          image: null,
        },
        optional_title: true,
        annotation: true,
      },
      used_in_restaurants: null,
    };

    // EXECUTE
    const result = pickEntries(entry, pickPaths, transferSetupModel);

    // VERIFY
    const expected = {
      "api::cookbook.cookbook[1].title": "For Every Day of the Year II",
      "api::cookbook.cookbook[1].recipes[1].name": "Potato Salad",
      "api::cookbook.cookbook[1].recipes[1].recipe": "Peel the potatoes, mix it with all the ingredients and you're done. Bon apetit!",
      "api::cookbook.cookbook[1].recipes[1].author_name": "Mr. Potato Head",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image_title": "Raw potatoes",
      "api::cookbook.cookbook[1].recipes[1].gallery[1].image_description": "Fresh!",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image_title": "Salad",
      "api::cookbook.cookbook[1].recipes[1].gallery[2].image_description": "Yummy!",
      "api::cookbook.cookbook[1].recipes[1].ingredients[1].name": "Potatoes",
      "api::cookbook.cookbook[1].recipes[1].ingredients[1].unit": "kg",
      "api::cookbook.cookbook[1].recipes[1].ingredients[2].name": "Peas",
      "api::cookbook.cookbook[1].recipes[1].ingredients[2].unit": "can",
      "api::cookbook.cookbook[1].recipes[1].ingredients[3].name": "Corn",
      "api::cookbook.cookbook[1].recipes[1].ingredients[3].unit": "can",
      "api::cookbook.cookbook[1].recipes[1].ingredients[4].name": "Mayo",
      "api::cookbook.cookbook[1].recipes[1].ingredients[4].unit": "spoons",
      "api::cookbook.cookbook[1].recipes[1].ingredients[5].name": "Cheese",
      "api::cookbook.cookbook[1].recipes[1].ingredients[5].unit": "block",
      "api::cookbook.cookbook[1].recipes[1].ingredients[6].name": "Apple",
      "api::cookbook.cookbook[1].recipes[1].ingredients[6].unit": "pcs",
      "api::cookbook.cookbook[1].gallery[1].annotation": "Check out our delicious meal, then read on and dive into the culinary heaven!",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image_title": "Cookbook",
      "api::cookbook.cookbook[1].gallery[1].main_image[3].image_description": "Booklet II",
      "api::cookbook.cookbook[1].gallery[1].gallery[5].image_description": "The booklet and leaves and fork.",
      "api::cookbook.cookbook[1].gallery[1].gallery[4].image_title": "Spices",
    };

    expect(result).toEqual(expected);
  });

  it("should pick entries correctly case C", () => {
    // SETUP
    const entry = {
      "api::course.course[1].title": "Math Basics",
      "api::course.course[1].description": "Learn the basics of Math. You won't be smarter than Archimedes or Thales of Miletus, but you'll be smarter than a new-born baby.",
      "api::course.course[1].chapters[1].title": "1. Addition",
      "api::course.course[1].chapters[1].lessons[1].title": "Lecture: Addition",
      "api::course.course[1].chapters[1].lessons[1].start_time": "2022-09-28T09:00:00.000Z",
      "api::course.course[1].chapters[1].lessons[1].duration": "03:00:00.000",
      "api::course.course[1].chapters[1].lessons[1].description": "## Description\n\nIn this lesson, we'll learn about addition and what rules to follow...",
      "api::course.course[1].chapters[1].lessons[1].lesson_type[1].__component": "lesson.lecture",
      "api::course.course[1].chapters[1].lessons[1].lesson_type[1].content": "You need to follow these rules:\na) add one number to the other\nb) do not subtract nor multiply\nc) ...",
      "api::course.course[1].chapters[1].lessons[2].title": "Test: Addition",
      "api::course.course[1].chapters[1].lessons[2].start_time": "2022-10-01T13:00:00.000Z",
      "api::course.course[1].chapters[1].lessons[2].duration": "02:00:00.000",
      "api::course.course[1].chapters[1].lessons[2].description": "Test your skills we've learnt in the previous lesson.",
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].__component": "lesson.quiz",
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].title": "Choose the correct answer",
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[1].question": "1 + 1 = ",
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[1].is_active": true,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[1].question_number": 1,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[2].question": "5 + 15 = ",
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[2].is_active": false,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[2].question_number": 2,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[3].question": "How many cups are on the photo?",
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[3].is_active": false,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].questions[3].question_number": 3,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].answers[1].question_number": 1,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].answers[1].correct_answer": "2",
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].answers[2].question_number": 2,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].answers[2].correct_answer": "20",
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].answers[3].question_number": 3,
      "api::course.course[1].chapters[1].lessons[2].lesson_type[1].answers[3].correct_answer": "15",
      "api::course.course[1].gallery[40].main_image[173].image_title": "Multicolored abacus",
      "api::course.course[1].gallery[40].main_image[173].image_description": "Use it to learn how to count from one to hundred.",
      "api::course.course[1].gallery[40].main_image[173].image[14].name": "crissy-jarvis-cHhbULJbPwM-unsplash.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].alternativeText": "crissy-jarvis-cHhbULJbPwM-unsplash.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].caption": "crissy-jarvis-cHhbULJbPwM-unsplash.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].width": 4288,
      "api::course.course[1].gallery[40].main_image[173].image[14].height": 2848,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.thumbnail.name": "thumbnail_crissy-jarvis-cHhbULJbPwM-unsplash.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.thumbnail.hash": "thumbnail_crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.thumbnail.ext": ".jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.thumbnail.mime": "image/jpeg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.thumbnail.width": 235,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.thumbnail.height": 156,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.thumbnail.size": 4.24,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.thumbnail.url": "/uploads/thumbnail_crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.large.name": "large_crissy-jarvis-cHhbULJbPwM-unsplash.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.large.hash": "large_crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.large.ext": ".jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.large.mime": "image/jpeg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.large.width": 1000,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.large.height": 664,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.large.size": 37,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.large.url": "/uploads/large_crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.medium.name": "medium_crissy-jarvis-cHhbULJbPwM-unsplash.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.medium.hash": "medium_crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.medium.ext": ".jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.medium.mime": "image/jpeg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.medium.width": 750,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.medium.height": 498,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.medium.size": 23.96,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.medium.url": "/uploads/medium_crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.small.name": "small_crissy-jarvis-cHhbULJbPwM-unsplash.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.small.hash": "small_crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.small.ext": ".jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.small.mime": "image/jpeg",
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.small.width": 500,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.small.height": 332,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.small.size": 13.05,
      "api::course.course[1].gallery[40].main_image[173].image[14].formats.small.url": "/uploads/small_crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].hash": "crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e",
      "api::course.course[1].gallery[40].main_image[173].image[14].ext": ".jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].mime": "image/jpeg",
      "api::course.course[1].gallery[40].main_image[173].image[14].size": 370.78,
      "api::course.course[1].gallery[40].main_image[173].image[14].url": "/uploads/crissy_jarvis_c_Hhb_UL_Jb_Pw_M_unsplash_fc35a7227e.jpg",
      "api::course.course[1].gallery[40].main_image[173].image[14].provider": "local",
      "api::course.course[1].gallery[40].gallery[174].image_title": "Fractions",
      "api::course.course[1].gallery[40].gallery[174].image_description": "We won't teach you that here!",
      "api::course.course[1].gallery[40].gallery[174].image[15].name": "chris-liverani-ViEBSoZH6M4-unsplash.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].alternativeText": "chris-liverani-ViEBSoZH6M4-unsplash.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].caption": "chris-liverani-ViEBSoZH6M4-unsplash.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].width": 3024,
      "api::course.course[1].gallery[40].gallery[174].image[15].height": 4032,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.thumbnail.name": "thumbnail_chris-liverani-ViEBSoZH6M4-unsplash.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.thumbnail.hash": "thumbnail_chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.thumbnail.ext": ".jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.thumbnail.mime": "image/jpeg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.thumbnail.width": 117,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.thumbnail.height": 156,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.thumbnail.size": 5.88,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.thumbnail.url": "/uploads/thumbnail_chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.large.name": "large_chris-liverani-ViEBSoZH6M4-unsplash.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.large.hash": "large_chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.large.ext": ".jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.large.mime": "image/jpeg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.large.width": 750,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.large.height": 1000,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.large.size": 107.3,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.large.url": "/uploads/large_chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.medium.name": "medium_chris-liverani-ViEBSoZH6M4-unsplash.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.medium.hash": "medium_chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.medium.ext": ".jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.medium.mime": "image/jpeg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.medium.width": 563,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.medium.height": 750,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.medium.size": 64.66,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.medium.url": "/uploads/medium_chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.small.name": "small_chris-liverani-ViEBSoZH6M4-unsplash.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.small.hash": "small_chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.small.ext": ".jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.small.mime": "image/jpeg",
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.small.width": 375,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.small.height": 500,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.small.size": 34.31,
      "api::course.course[1].gallery[40].gallery[174].image[15].formats.small.url": "/uploads/small_chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].hash": "chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2",
      "api::course.course[1].gallery[40].gallery[174].image[15].ext": ".jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].mime": "image/jpeg",
      "api::course.course[1].gallery[40].gallery[174].image[15].size": 885.07,
      "api::course.course[1].gallery[40].gallery[174].image[15].url": "/uploads/chris_liverani_Vi_EB_So_ZH_6_M4_unsplash_aef91e05a2.jpg",
      "api::course.course[1].gallery[40].gallery[174].image[15].provider": "local",
    };

    const pickPaths = [
      "api::course.course.title",
      "api::course.course.description",
      "api::course.course.gallery.main_image.image_title",
      "api::course.course.gallery.main_image.image_description",
      "api::course.course.gallery.gallery.image_title",
      "api::course.course.gallery.gallery.image_description",
      "api::course.course.gallery.optional_title",
      "api::course.course.gallery.annotation",
      "api::course.course.id",
    ];

    const transferSetupModel = {
      __model__: true,
      title: true,
      description: true,
      chapters: null,
      gallery: {
        main_image: {
          image_title: true,
          image_description: true,
          image: null,
        },
        gallery: {
          image_title: true,
          image_description: true,
          image: null,
        },
        optional_title: true,
        annotation: true,
      },
    };

    // EXECUTE
    const result = pickEntries(entry, pickPaths, transferSetupModel);

    // VERIFY
    const expected = {
      "api::course.course[1].title": "Math Basics",
      "api::course.course[1].description": "Learn the basics of Math. You won't be smarter than Archimedes or Thales of Miletus, but you'll be smarter than a new-born baby.",
      "api::course.course[1].gallery[40].main_image[173].image_title": "Multicolored abacus",
      "api::course.course[1].gallery[40].main_image[173].image_description": "Use it to learn how to count from one to hundred.",
      "api::course.course[1].gallery[40].gallery[174].image_title": "Fractions",
      "api::course.course[1].gallery[40].gallery[174].image_description": "We won't teach you that here!",
    };

    expect(result).toEqual(expected);
  });

  it("should correctly pick paths from entry including a Dynamic Zone", () => {
    // SETUP
    const entry = {
      "api::lesson.lesson[1].title": "Lecture: Addition",
      "api::lesson.lesson[1].start_time": "2022-09-28T09:00:00.000Z",
      "api::lesson.lesson[1].duration": "03:00:00.000",
      "api::lesson.lesson[1].description": "## Description\n\nIn this lesson, we'll learn about addition and what rules to follow...",
      "api::lesson.lesson[1].lesson_type[1;lesson.lecture].__component": "lesson.lecture",
      "api::lesson.lesson[1].lesson_type[1;lesson.lecture].content": "You need to follow these rules:\na) add one number to the other\nb) do not subtract nor multiply\nc) ...",
    };

    const pickPaths = [
      "api::lesson.lesson.title",
      "api::lesson.lesson.description",
      "api::lesson.lesson.lesson_type[lecture].content",
      "api::lesson.lesson.lesson_type[survey].description",
      "api::lesson.lesson.lesson_type[survey].questions.question",
      "api::lesson.lesson.lesson_type[quiz].title",
      "api::lesson.lesson.lesson_type[quiz].questions.question",
      "api::lesson.lesson.lesson_type[quiz].answers.correct_answer",
      "api::lesson.lesson.id",
    ];

    const transferSetupModel = {
      __model__: true,
      title: true,
      start_time: null,
      duration: null,
      description: true,
      lesson_type: [
        {
          __component__: "lesson.lecture",
          content: false,
        },
        {
          __component__: "lesson.survey",
          description: true,
          questions: {
            question: true,
            is_active: null,
            assets: null,
            question_number: null,
          },
        },
        {
          __component__: "lesson.quiz",
          title: true,
          questions: {
            question: true,
            is_active: null,
            assets: null,
            question_number: null,
          },
          answers: {
            question_number: null,
            correct_answer: true,
            answer_asset: null,
          },
        },
      ],
    };

    // EXECUTE
    const result = pickEntries(entry, pickPaths, transferSetupModel);

    // VERIFY
    const expected = {
      "api::lesson.lesson[1].title": "Lecture: Addition",
      "api::lesson.lesson[1].description": "## Description\n\nIn this lesson, we'll learn about addition and what rules to follow...",
      "api::lesson.lesson[1].lesson_type[1;lesson.lecture].content": "You need to follow these rules:\na) add one number to the other\nb) do not subtract nor multiply\nc) ...",
    }

    expect(result).toEqual(expected);
  });
});
