"use strict";

const parsedLocalazyEntryToUpdateEntry = require("../parsed-localazy-entry-to-update-entry");
const allModels = require("../../tests/fixtures/strapi-plugin-all-models");
const {
  localazyEntry,
  fullyPopulatedLocalizedEntry,
  currentEntry,
  baseEntry,
  uid,
  locale,
} = require("../../tests/fixtures/parsed-localazy-entry-to-update-entry");

describe("parsed-localazy-entry-to-update-entry.js", () => {
  it("should return transformed 'cookbook' entry to strapi update entry structure", async () => {
    // EXECUTE
    const result = await parsedLocalazyEntryToUpdateEntry(
      allModels,
      localazyEntry,
      fullyPopulatedLocalizedEntry,
      currentEntry,
      baseEntry,
      uid,
      locale
    );

    // VERIFY
    const expected = {
      id: 24,
      title: "Pro každý den v roce",
      author_name: "David V.",
      pages: 365,
      recipes: [
        {
          id: 20,
          name: "Bramborový salát",
          recipe: "Oloupejte brambory, smíchejte je se všemi ingrediencemi a máte hotovo. Bon apetit!",
          estimated_cook_time: "00:30:00.000",
          difficulty: "easy",
          author_name: "Mr. Bramborová hlava",
          gallery: [
            {
              id: 100,
              image_title: "Syrové brambory",
              image_description: "Čerstvý!",
              image: {
                id: 6,
                name: "rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
                alternativeText: "rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
                caption: "rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
                width: 2268,
                height: 4032,
                formats: {
                  thumbnail: {
                    name: "thumbnail_rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
                    hash: "thumbnail_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 88,
                    height: 156,
                    size: 5.35,
                    url: "/uploads/thumbnail_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
                  },
                  large: {
                    name: "large_rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
                    hash: "large_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 563,
                    height: 1000,
                    size: 108.15,
                    url: "/uploads/large_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
                  },
                  medium: {
                    name: "medium_rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
                    hash: "medium_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 422,
                    height: 750,
                    size: 65.52,
                    url: "/uploads/medium_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
                  },
                  small: {
                    name: "small_rodrigo-dos-reis-h3AkzboxK4Q-unsplash.jpg",
                    hash: "small_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 281,
                    height: 500,
                    size: 34.23,
                    url: "/uploads/small_rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
                  },
                },
                hash: "rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 1081.59,
                url: "/uploads/rodrigo_dos_reis_h3_Akzbox_K4_Q_unsplash_d17e795cea.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
              },
            },
            {
              id: 101,
              image_title: "Salát",
              image_description: "Mňam!",
              image: {
                id: 7,
                name: "jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
                alternativeText: "jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
                caption: "jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
                width: 4608,
                height: 3456,
                formats: {
                  thumbnail: {
                    name: "thumbnail_jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
                    hash: "thumbnail_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 208,
                    height: 156,
                    size: 9.03,
                    url: "/uploads/thumbnail_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
                  },
                  large: {
                    name: "large_jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
                    hash: "large_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 1000,
                    height: 750,
                    size: 102.77,
                    url: "/uploads/large_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
                  },
                  medium: {
                    name: "medium_jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
                    hash: "medium_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 750,
                    height: 563,
                    size: 66.26,
                    url: "/uploads/medium_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
                  },
                  small: {
                    name: "small_jeffrey-betts-PeyzQt7tMk0-unsplash.jpg",
                    hash: "small_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
                    ext: ".jpg",
                    mime: "image/jpeg",
                    path: null,
                    width: 500,
                    height: 375,
                    size: 35.17,
                    url: "/uploads/small_jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
                  },
                },
                hash: "jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 1664.79,
                url: "/uploads/jeffrey_betts_Peyz_Qt7t_Mk0_unsplash_9650d628db.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
              },
            },
          ],
          ingredients: [
            {
              id: 115,
              name: "Brambory",
              amount: 2,
              unit: "kg",
              is_required: true,
            },
            {
              id: 116,
              name: "Hrášek",
              amount: 0.5,
              unit: "plechovka",
              is_required: true,
            },
            {
              id: 117,
              name: "Kukuřice",
              amount: 0.5,
              unit: "plechovka",
              is_required: true,
            },
            {
              id: 118,
              name: "Majonéza",
              amount: 4,
              unit: "1",
              is_required: true,
            },
            {
              id: 119,
              name: "Sýr",
              amount: 1,
              unit: "1",
              is_required: true,
            },
            {
              id: 120,
              name: "Jablko",
              amount: 1,
              unit: "ks",
              is_required: true,
            },
          ],
        },
      ],
      gallery: {
        id: 24,
        optional_title: null,
        annotation: "Podívejte se na naše chutné jídlo, pak čtěte dál a ponořte se do kulinářského nebe!",
        main_image: {
          id: 102,
          image_title: "Kuchařka",
          image_description: "Booklet",
          image: {
            id: 9,
            name: "dan-gold-5O1ddenSM4g-unsplash.jpg",
            alternativeText: "dan-gold-5O1ddenSM4g-unsplash.jpg",
            caption: "dan-gold-5O1ddenSM4g-unsplash.jpg",
            width: 6000,
            height: 3376,
            formats: {
              thumbnail: {
                name: "thumbnail_dan-gold-5O1ddenSM4g-unsplash.jpg",
                hash: "thumbnail_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
                ext: ".jpg",
                mime: "image/jpeg",
                path: null,
                width: 245,
                height: 138,
                size: 7.44,
                url: "/uploads/thumbnail_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
              },
              large: {
                name: "large_dan-gold-5O1ddenSM4g-unsplash.jpg",
                hash: "large_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
                ext: ".jpg",
                mime: "image/jpeg",
                path: null,
                width: 1000,
                height: 563,
                size: 52.67,
                url: "/uploads/large_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
              },
              medium: {
                name: "medium_dan-gold-5O1ddenSM4g-unsplash.jpg",
                hash: "medium_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
                ext: ".jpg",
                mime: "image/jpeg",
                path: null,
                width: 750,
                height: 422,
                size: 35.15,
                url: "/uploads/medium_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
              },
              small: {
                name: "small_dan-gold-5O1ddenSM4g-unsplash.jpg",
                hash: "small_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
                ext: ".jpg",
                mime: "image/jpeg",
                path: null,
                width: 500,
                height: 281,
                size: 19.95,
                url: "/uploads/small_dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
              },
            },
            hash: "dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 972.68,
            url: "/uploads/dan_gold_5_O1dden_SM_4g_unsplash_5adef7d907.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
          },
        },
        gallery: [
          {
            id: 103,
            image_title: null,
            image_description: "Brožura, listy a vidlička.",
            image: {
              id: 11,
              name: "heather-ford-G4LFhuLXhLE-unsplash.jpg",
              alternativeText: "heather-ford-G4LFhuLXhLE-unsplash.jpg",
              caption: "heather-ford-G4LFhuLXhLE-unsplash.jpg",
              width: 6127,
              height: 3844,
              formats: {
                thumbnail: {
                  name: "thumbnail_heather-ford-G4LFhuLXhLE-unsplash.jpg",
                  hash: "thumbnail_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
                  ext: ".jpg",
                  mime: "image/jpeg",
                  path: null,
                  width: 245,
                  height: 154,
                  size: 9.54,
                  url: "/uploads/thumbnail_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
                },
                large: {
                  name: "large_heather-ford-G4LFhuLXhLE-unsplash.jpg",
                  hash: "large_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
                  ext: ".jpg",
                  mime: "image/jpeg",
                  path: null,
                  width: 1000,
                  height: 628,
                  size: 117.56,
                  url: "/uploads/large_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
                },
                medium: {
                  name: "medium_heather-ford-G4LFhuLXhLE-unsplash.jpg",
                  hash: "medium_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
                  ext: ".jpg",
                  mime: "image/jpeg",
                  path: null,
                  width: 750,
                  height: 471,
                  size: 66.32,
                  url: "/uploads/medium_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
                },
                small: {
                  name: "small_heather-ford-G4LFhuLXhLE-unsplash.jpg",
                  hash: "small_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
                  ext: ".jpg",
                  mime: "image/jpeg",
                  path: null,
                  width: 500,
                  height: 314,
                  size: 31.42,
                  url: "/uploads/small_heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
                },
              },
              hash: "heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f",
              ext: ".jpg",
              mime: "image/jpeg",
              size: 6971.47,
              url: "/uploads/heather_ford_G4_L_Fhu_L_Xh_LE_unsplash_7a2c2cac8f.jpg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
            },
          },
          {
            id: 104,
            image_title: "Koření",
            image_description: null,
            image: {
              id: 10,
              name: "calum-lewis-vA1L1jRTM70-unsplash.jpg",
              alternativeText: "calum-lewis-vA1L1jRTM70-unsplash.jpg",
              caption: "calum-lewis-vA1L1jRTM70-unsplash.jpg",
              width: 3569,
              height: 5353,
              formats: {
                thumbnail: {
                  name: "thumbnail_calum-lewis-vA1L1jRTM70-unsplash.jpg",
                  hash: "thumbnail_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
                  ext: ".jpg",
                  mime: "image/jpeg",
                  path: null,
                  width: 104,
                  height: 156,
                  size: 5.55,
                  url: "/uploads/thumbnail_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
                },
                large: {
                  name: "large_calum-lewis-vA1L1jRTM70-unsplash.jpg",
                  hash: "large_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
                  ext: ".jpg",
                  mime: "image/jpeg",
                  path: null,
                  width: 667,
                  height: 1000,
                  size: 116.32,
                  url: "/uploads/large_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
                },
                medium: {
                  name: "medium_calum-lewis-vA1L1jRTM70-unsplash.jpg",
                  hash: "medium_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
                  ext: ".jpg",
                  mime: "image/jpeg",
                  path: null,
                  width: 500,
                  height: 750,
                  size: 72.75,
                  url: "/uploads/medium_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
                },
                small: {
                  name: "small_calum-lewis-vA1L1jRTM70-unsplash.jpg",
                  hash: "small_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
                  ext: ".jpg",
                  mime: "image/jpeg",
                  path: null,
                  width: 333,
                  height: 500,
                  size: 36.52,
                  url: "/uploads/small_calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
                },
              },
              hash: "calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997",
              ext: ".jpg",
              mime: "image/jpeg",
              size: 2305.97,
              url: "/uploads/calum_lewis_v_A1_L1j_RTM_70_unsplash_5aff3a8997.jpg",
              previewUrl: null,
              provider: "local",
              provider_metadata: null,
            },
          },
        ],
      },
    };

    expect(result).toEqual(expected);
  });
});
