export default {
  LOCALAZY_OAUTH_URL: "https://localazy.com/oauth/authorize",
  LOCALAZY_OAUTH_APP_CLIENT_ID: "18395772851999073783",
  LOCALAZY_PLUGIN_CONNECTOR_API_URL:
    "https://plugins.localazy.com/generic-connector",
  LOCALAZY_PUBLIC_API_URL: "https://api.localazy.com",
  LOCALAZY_PLUGIN_ID: "1",
  LOCALAZY_DEFAULT_FILE_NAME: "strapi.json",
  LOCALAZY_DEFAULT_FILE_PATH: "",
  LOCALAZY_DEFAULT_FILE_EXTENSION: "json",
  LOCALAZY_DEFAULT_LOCALE: "en",
  LOCALAZY_API_USER_JWT_COOKIE_NAME: "LOCALAZY-API-USER-JWT",
  LOCALAZY_API_USER_COOKIE_EXPIRATION: 7,
  LOCALAZY_PUBLIC_API_LIFTED_LIMITS: true,
};
