export default {
  LOCALAZY_OAUTH_URL: "https://testing.localazy.com/oauth/authorize",
  LOCALAZY_OAUTH_APP_CLIENT_ID: "18503917571895066466",
  LOCALAZY_PLUGIN_CONNECTOR_API_URL: "https://testing.localazy.com/plugin-connector",
  LOCALAZY_PUBLIC_API_URL: "https://testing.localazy.com/pubapi",
  LOCALAZY_PLUGIN_ID: "1",
  LOCALAZY_DEFAULT_FILE_NAME: "strapi.json",
  LOCALAZY_DEFAULT_FILE_PATH: "",
  LOCALAZY_DEFAULT_FILE_EXTENSION: "json",
  LOCALAZY_DEFAULT_LOCALE: "en",
  LOCALAZY_API_USER_JWT_COOKIE_NAME: "LOCALAZY-API-USER-JWT",
  LOCALAZY_API_USER_COOKIE_EXPIRATION: 7,
  LOCALAZY_PUBLIC_API_LIFTED_LIMITS: true,
};
