"use strict";

module.exports = {
  LOCALAZY_OAUTH_URL: "",
  LOCALAZY_OAUTH_APP_CLIENT_ID: "",
  LOCALAZY_PLUGIN_CONNECTOR_API_URL: "",
  LOCALAZY_PUBLIC_API_URL: "",
  LOCALAZY_PLUGIN_ID: "",
  LOCALAZY_DEFAULT_FILE_NAME: "",
  LOCALAZY_DEFAULT_FILE_PATH: "",
  LOCALAZY_DEFAULT_FILE_EXTENSION: "",
  LOCALAZY_DEFAULT_LOCALE: "",
  LOCALAZY_API_USER_JWT_COOKIE_NAME: "",
  LOCALAZY_API_USER_COOKIE_EXPIRATION: -1,
  LOCALAZY_PUBLIC_API_LIFTED_LIMITS: false,
};
